---
abstract: 'dumping database (DBI) data into a CSV.'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  DBI: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  perl: 5.008_001
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-CSVDumper
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  DBIx::CSVDumper:
    file: lib/DBIx/CSVDumper.pm
    version: 0.01
requires:
  Encode: 0
  Text::CSV: 0
resources:
  bugtracker: https://github.com/Songmu/p5-DBIx-CSVDumper/issues
  homepage: https://github.com/Songmu/p5-DBIx-CSVDumper
  repository: git://github.com/Songmu/p5-DBIx-CSVDumper.git
version: 0.01
